### ISSUE TITLE
Issue with xdebug 3.3.0 

### ISSUE THREAD

**Issue by am4rth** [php-defer/php-defer#45]
This is not a problem with php-defer itself, but as it relies on `__destruct()` it can cause problems:

There is currently a bug in xdebug 3.3.0 https://bugs.xdebug.org/view.php?id=2222 that causes destructors to not be called correctly/in the expected order when exceptions are thrown. This behavior only seems to occur when xdebug is in `develop` mode.

In combination with php-defer this can lead to very obscure behavior which is difficult to debug.

A reference to the problem in the readme (or this issue here) may help others to debug.

Kudos to [@lrotermund ](https://github.com/lrotermund) for helping!

**Comment by bkrukowski** [comment]
@am4rth thanks! Could you please prepare a small example that shows the problem?

**Comment by bkrukowski** [comment]
Closing due to lack of details
